on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: paper

jobs:
  paper:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc
      - uses: r-lib/actions/setup-tinytex
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Render
        run: |
          devtools::document()
          devtools::load_all()
          rmarkdown::render("vignettes/paper.Rmd", output_format =  "all")
        shell: Rscript {0}
      - name: Upload
      - uses: actions/upload-artifact@v2
        with:
          name: paper
          path: vignettes
          if-no-files-found: error
